version: '3'
services:
  bookstack:
    user: root
    image: solidnerd/bookstack:23.2
    container_name: bookstack
    restart: always
    ports:
      - "8080:8080"
    networks:
      - bookstack
    volumes:
      - "./.env:/var/www/bookstack/.env"
networks:
  bookstack:
      external: true

